version: '3.9'

services:
    postgres:
        image: postgres:latest
        container_name: postgres_container
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: 123456
            POSTGRES_DB: grocery_store
            PGDATA: /var/lib/postgresql/data/pgdata
        ports:
            - "5432:5432"
        volumes:
            - ./packages/server/pgdata:/var/lib/postgresql/data/pgdata
        deploy:
            resources:
                limits:
                    cpus: '0.50'
                    memory: 512M
                reservations:
                    cpus: '0.25'
                    memory: 256M
        command: >
            postgres -c max_connections=1000
                     -c shared_buffers=256MB
                     -c effective_cache_size=768MB
                     -c maintenance_work_mem=64MB
                     -c checkpoint_completion_target=0.7
                     -c wal_buffers=16MB
                     -c default_statistics_target=100
        healthcheck:
            test: [ "CMD-SHELL", "pg_isready -U postgres -d grocery_store" ]
            interval: 30s
            timeout: 10s
            retries: 5
        restart: unless-stopped
        tty: true
        stdin_open: true
    server:
        container_name: server
        build:
            context: ./packages/server
            dockerfile: Dockerfile
        ports:
            - "8080:8080"
        environment:
            DATABASE_URL: "${DATABASE_URL}"
            PORT: "${API_PORT}"
        depends_on:
            postgres:
                condition: service_healthy
volumes:
    pgdata:
        driver: local
